/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CalendarIdImport } from './routes/calendar/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CalendarIdRoute = CalendarIdImport.update({
  path: '/calendar/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar/$id': {
      id: '/calendar/$id'
      path: '/calendar/$id'
      fullPath: '/calendar/$id'
      preLoaderRoute: typeof CalendarIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar/$id': typeof CalendarIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar/$id': typeof CalendarIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calendar/$id': typeof CalendarIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar/$id'
  id: '__root__' | '/' | '/calendar/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarIdRoute: typeof CalendarIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarIdRoute: CalendarIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calendar/$id": {
      "filePath": "calendar/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
