/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EntrypageImport } from './routes/Entrypage'
import { Route as CalpageImport } from './routes/Calpage'

// Create/Update Routes

const EntrypageRoute = EntrypageImport.update({
  path: '/Entrypage',
  getParentRoute: () => rootRoute,
} as any)

const CalpageRoute = CalpageImport.update({
  path: '/Calpage',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Calpage': {
      id: '/Calpage'
      path: '/Calpage'
      fullPath: '/Calpage'
      preLoaderRoute: typeof CalpageImport
      parentRoute: typeof rootRoute
    }
    '/Entrypage': {
      id: '/Entrypage'
      path: '/Entrypage'
      fullPath: '/Entrypage'
      preLoaderRoute: typeof EntrypageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Calpage': typeof CalpageRoute
  '/Entrypage': typeof EntrypageRoute
}

export interface FileRoutesByTo {
  '/Calpage': typeof CalpageRoute
  '/Entrypage': typeof EntrypageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Calpage': typeof CalpageRoute
  '/Entrypage': typeof EntrypageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Calpage' | '/Entrypage'
  fileRoutesByTo: FileRoutesByTo
  to: '/Calpage' | '/Entrypage'
  id: '__root__' | '/Calpage' | '/Entrypage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CalpageRoute: typeof CalpageRoute
  EntrypageRoute: typeof EntrypageRoute
}

const rootRouteChildren: RootRouteChildren = {
  CalpageRoute: CalpageRoute,
  EntrypageRoute: EntrypageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/Calpage",
        "/Entrypage"
      ]
    },
    "/Calpage": {
      "filePath": "Calpage.jsx"
    },
    "/Entrypage": {
      "filePath": "Entrypage.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
