name: Deploy

concurrency:
  group: prod
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "web: Extract metadata (tags, labels) for Docker"
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/newbies-workplace/calendar-web

#      - name: "web: Create .env"
#        uses: iamsauravsharma/create-dotenv@v1.2.2
#        with:
#          file-name: '.env'
#        env:
#          RETRO_WEB_API_URL: ${{ secrets.RETRO_WEB_API_URL }}
#          RETRO_WEB_SOCKET_URL: ${{ secrets.RETRO_WEB_SOCKET_URL }}

      - name: "web: Build and push Docker image"
        uses: docker/build-push-action@v3
        with:
          context: .
          target: calendar-web
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    needs: [ docker ]

    steps:
      - name: Deploy package to production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd calendar/web
            docker-compose down
            docker image rm ghcr.io/newbies-workplace/calendar-web || true
            docker pull ghcr.io/newbies-workplace/calendar-web:latest
            docker-compose up -d
